code4romania/practice-for-good

src/assets/locales/ro/translation.json
src/common/constants/CounterType.constants.ts
src/common/constants/nomenclature.constants.ts
src/pages/landing/Landing.tsx
src/pages/landing/components/counter/Counter.tsx
src/pages/landing/components/counter/CounterItem.tsx

[C4R-823](https://wearetribus.atlassian.net/browse/C4R-823) - landing counter component

feat: [C4R-823] landing counter component

---

src/assets/locales/ro/translation.json
src/common/interfaces/ContactMail.interface.ts
src/pages/contact/Contact.tsx
src/pages/contact/configs/Contact.config.ts
src/services/public/PublicApi.queries.ts
src/services/public/PublicApi.service.ts

[C4R-818](https://wearetribus.atlassian.net/browse/C4R-818)

feat: [C4R-818] call API to send mail

---

src/common/constants/MailAppType.constants.ts
src/common/interfaces/ContactMail.interface.ts
src/pages/contact/Contact.tsx
src/pages/contact/configs/Contact.config.ts

[C4R-909](https://wearetribus.atlassian.net/browse/C4R-909)
updates to interface

feat: [C4R-909] added app type to subject

---

src/common/constants/nomenclature.constants.ts
src/pages/landing/Landing.tsx
src/pages/landing/components/domains/Domain.tsx
src/pages/landing/components/domains/Domains.tsx

[C4R-903](https://wearetribus.atlassian.net/browse/C4R-903)

feat: [C4R-903] added search by domain from landing page

---

src/assets/locales/ro/translation.json
src/pages/programs/components/ProgramItem.tsx

[C4R-1189](https://wearetribus.atlassian.net/browse/C4R-1189)

fix: [C4R-1189] missing word from card for number of hours

---

src/common/components/search-field/SearchField.tsx

[C4R-1165](https://wearetribus.atlassian.net/browse/C4R-1165)

fix: [C4R-1165] added max length to search field

---

src/common/components/ngo-search/NGOSearch.tsx
src/common/components/practice-programs-search/PracticeProgramsSearch.tsx

[C4R-1167](https://wearetribus.atlassian.net/browse/C4R-1167)

fix: [C4R-1167] removed leading and trailing white spaces from search

---

src/common/components/ngo-filter-modal/NGOFilterModal.tsx
src/common/components/ngo-search/NGOSearch.tsx
src/common/components/practice-program-filter-modal/PracticeProgramFilterModal.tsx
src/common/components/practice-programs-search/PracticeProgramsSearch.tsx
src/services/nomenclature/Nomeclature.queries.ts

[C4R-1187](https://wearetribus.atlassian.net/browse/C4R-1187) Make direct call to cities query rather than through useCitiesQuery

[C4R-1187] make direct call to cities query rather than through useCitiesQuery

---

src/common/components/shape-wrapper/ShapeWrapper.tsx
src/pages/programs/Program.tsx

[C4R-1401](https://wearetribus.atlassian.net/browse/C4R-1401)

fix: [C4R-1401] fixed error mesage on failing to load practice program

---

src/assets/locales/ro/translation.json
src/common/components/date-picker/DatePicker.tsx
src/common/components/header/Header.tsx
src/common/components/ngo-filter-modal/NGOFilterModal.tsx
src/common/components/ngo-search/NGOSearch.tsx
src/common/components/practice-program-filter-modal/PracticeProgramFilterModal.tsx
src/common/components/practice-programs-search/PracticeProgramsSearch.tsx
src/common/components/search-field/SearchField.tsx
src/common/components/select/Select.tsx
src/common/components/server-select/ServerSelect.tsx
src/common/components/sliding-menu/SlidingMenu.tsx
src/common/helpers/Format.helper.ts
src/index.css
src/pages/organizations/components/OrganizationItem.tsx
src/pages/programs/Program.tsx
src/react-app-env.d.ts

[1193](https://wearetribus.atlassian.net/browse/C4R-1193) Reset input filters by adding clear
[1226](https://wearetribus.atlassian.net/browse/C4R-1226) Reset date filter
- Add county mapping for location search
- clear all for all inputs

[Bugfix] Search form input fixes

---

src/pages/contact/configs/Contact.config.ts

[C4R-1259](https://wearetribus.atlassian.net/browse/C4R-1259)

fix: [C4R-1259] updated contact form field validations

---

src/assets/locales/ro/translation.json
src/pages/contact/configs/Contact.config.ts

[C4R-1259](https://wearetribus.atlassian.net/browse/C4R-1259)

fix: [C4R-1259] wrong validation translations

---

src/assets/locales/ro/translation.json
src/common/components/ngo-filter-modal/NGOFilterModal.tsx
src/common/components/practice-program-filter-modal/PracticeProgramFilterModal.tsx
src/common/components/select/Select.tsx
src/common/hooks/useToast.ts

[C4R-1399](https://wearetribus.atlassian.net/browse/C4R-1399)

fix: [C4R-1399] added reset filters button for mobile

---

src/common/interfaces/Organization.interface.ts
src/pages/organizations/components/OrganizationDetails.tsx

[C4R-1209](https://wearetribus.atlassian.net/browse/C4R-1209)

fix: [C4R-1209] changed contact data displayed when viewing one ong

---

src/pages/landing/components/domains/Domain.tsx

[C4R-1402](https://wearetribus.atlassian.net/browse/C4R-1402)

fix: [C4R-1402] added max width to domain card

---

src/common/router/Router.tsx
src/common/scroll-to-top/ScrollToTop.jsx

Bug [C4R-1362](https://wearetribus.atlassian.net/browse/C4R-1362)

C4R-1362 - Fixed scroll to top on page change

---

src/common/components/header/Header.tsx
src/common/components/ngo-search/NGOSearch.tsx
src/common/components/practice-programs-search/PracticeProgramsSearch.tsx
src/index.css
tailwind.config.js

Bug [C4R-1384](https://wearetribus.atlassian.net/browse/C4R-1384)

C4R-1362 - Added hover state on buttons

---

src/common/components/breadcrumbs/Breadcrumbs.tsx
src/common/components/virtuoso-header/VirtuosoHeader.tsx
src/common/constants/Menu.constants.ts
src/common/containers/Layout.tsx
src/common/router/Router.tsx
src/pages/organizations/Organization.tsx
src/pages/organizations/Organizations.tsx
src/pages/programs/Program.tsx
src/pages/programs/Programs.tsx
src/pages/programs/components/ProgramItem.tsx
src/services/organization/Organization.queries.ts
src/services/practice-programs/PracticePrograms.queries.ts
src/store/Selectors.ts
src/store/Store.ts
src/store/breadcrumbs-state/Breadcrumbs.selectors.ts
src/store/breadcrumbs-state/Breadcrumbs.slice.ts

Same: https://github.com/code4romania/centrucivic/pull/38

[C4R-1514] Refactor breadcrumbs

---

src/common/components/description/Description.tsx
src/common/components/footer/Footer.tsx
src/common/components/header/Header.tsx
src/common/components/infinite-scroll-footer/InfiniteScrollFooter.tsx
src/common/components/ngo-filter-modal/NGOFilterModal.tsx
src/common/components/ngo-search/NGOSearch.tsx
src/common/components/practice-program-filter-modal/PracticeProgramFilterModal.tsx
src/common/components/practice-programs-search/PracticeProgramsSearch.tsx
src/common/components/sliding-menu/SlidingMenu.tsx
src/common/components/virtuoso-header/VirtuosoHeader.tsx
src/common/containers/Layout.tsx
src/index.css
src/pages/about/About.tsx
src/pages/contact/Contact.tsx
src/pages/landing/Landing.tsx
src/pages/landing/components/counter/Counter.tsx
src/pages/landing/components/domains/Domains.tsx
src/pages/organizations/Organization.tsx
src/pages/organizations/Organizations.tsx
src/pages/organizations/components/OrganizationDetails.tsx
src/pages/programs/Program.tsx
src/pages/programs/Programs.tsx
tailwind.config.js

Task [C4R-1529](https://wearetribus.atlassian.net/browse/C4R-1529)

C4R-1529 - Fixed layout paddings and spacing

---

src/common/components/sliding-menu/SlidingMenu.tsx

Bug [C4R-1546](https://wearetribus.atlassian.net/browse/C4R-1546)

C4R-1546 - Fixed layout on sliding menu mobile
